# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'New_User.ui'
##
## Created by: Qt User Interface Compiler version 6.1.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *  # type: ignore
from PySide6.QtGui import *  # type: ignore
from PySide6.QtWidgets import *  # type: ignore


class Ui_NewUserWidget(object):
    def setupUi(self, NewUserWidget):
        if not NewUserWidget.objectName():
            NewUserWidget.setObjectName(u"NewUserWidget")
        NewUserWidget.resize(733, 670)
        NewUserWidget.setInputMethodHints(Qt.ImhNone)
        self.first_name_input = QLineEdit(NewUserWidget)
        self.first_name_input.setObjectName(u"first_name_input")
        self.first_name_input.setGeometry(QRect(20, 80, 321, 31))
        font = QFont()
        font.setPointSize(20)
        self.first_name_input.setFont(font)
        self.first_name_input.setTabletTracking(False)
        self.first_name_input.setFrame(True)
        self.first_name_input.setClearButtonEnabled(False)
        self.first_name_label = QLabel(NewUserWidget)
        self.first_name_label.setObjectName(u"first_name_label")
        self.first_name_label.setGeometry(QRect(20, 40, 171, 31))
        font1 = QFont()
        font1.setPointSize(24)
        font1.setBold(True)
        self.first_name_label.setFont(font1)
        self.first_name_label.setFocusPolicy(Qt.NoFocus)
        self.last_name_label = QLabel(NewUserWidget)
        self.last_name_label.setObjectName(u"last_name_label")
        self.last_name_label.setGeometry(QRect(380, 40, 171, 31))
        self.last_name_label.setFont(font1)
        self.last_name_input = QLineEdit(NewUserWidget)
        self.last_name_input.setObjectName(u"last_name_input")
        self.last_name_input.setGeometry(QRect(380, 80, 321, 31))
        self.last_name_input.setFont(font)
        self.new_email_label = QLabel(NewUserWidget)
        self.new_email_label.setObjectName(u"new_email_label")
        self.new_email_label.setGeometry(QRect(20, 280, 91, 31))
        self.new_email_label.setFont(font1)
        self.new_email_input = QLineEdit(NewUserWidget)
        self.new_email_input.setObjectName(u"new_email_input")
        self.new_email_input.setGeometry(QRect(20, 320, 321, 31))
        self.new_email_input.setFont(font)
        self.middle_name_label = QLabel(NewUserWidget)
        self.middle_name_label.setObjectName(u"middle_name_label")
        self.middle_name_label.setGeometry(QRect(20, 120, 211, 31))
        self.middle_name_label.setFont(font1)
        self.middle_name_input = QLineEdit(NewUserWidget)
        self.middle_name_input.setObjectName(u"middle_name_input")
        self.middle_name_input.setGeometry(QRect(20, 160, 321, 31))
        self.middle_name_input.setFont(font)
        self.phone_num_label = QLabel(NewUserWidget)
        self.phone_num_label.setObjectName(u"phone_num_label")
        self.phone_num_label.setGeometry(QRect(380, 280, 231, 31))
        self.phone_num_label.setFont(font1)
        self.phone_num_input = QLineEdit(NewUserWidget)
        self.phone_num_input.setObjectName(u"phone_num_input")
        self.phone_num_input.setGeometry(QRect(380, 320, 321, 31))
        self.phone_num_input.setFont(font)
        self.phone_num_input.setInputMethodHints(Qt.ImhDigitsOnly|Qt.ImhPreferNumbers)
        self.create_button = QPushButton(NewUserWidget)
        self.create_button.setObjectName(u"create_button")
        self.create_button.setEnabled(False)
        self.create_button.setGeometry(QRect(544, 630, 81, 25))
        font2 = QFont()
        font2.setPointSize(12)
        self.create_button.setFont(font2)
        self.cancel_button = QPushButton(NewUserWidget)
        self.cancel_button.setObjectName(u"cancel_button")
        self.cancel_button.setGeometry(QRect(630, 630, 81, 25))
        font3 = QFont()
        font3.setPointSize(12)
        font3.setBold(False)
        self.cancel_button.setFont(font3)
        self.gender_input = QLineEdit(NewUserWidget)
        self.gender_input.setObjectName(u"gender_input")
        self.gender_input.setGeometry(QRect(20, 240, 321, 31))
        self.gender_input.setFont(font)
        self.gende_label = QLabel(NewUserWidget)
        self.gende_label.setObjectName(u"gende_label")
        self.gende_label.setGeometry(QRect(20, 200, 111, 31))
        self.gende_label.setFont(font1)
        self.birth_date_label = QLabel(NewUserWidget)
        self.birth_date_label.setObjectName(u"birth_date_label")
        self.birth_date_label.setGeometry(QRect(380, 120, 351, 41))
        font4 = QFont()
        font4.setPointSize(20)
        font4.setBold(True)
        self.birth_date_label.setFont(font4)
        self.bday_month_input = QLineEdit(NewUserWidget)
        self.bday_month_input.setObjectName(u"bday_month_input")
        self.bday_month_input.setGeometry(QRect(380, 160, 71, 31))
        self.bday_month_input.setFont(font)
        self.bday_month_input.setMaxLength(2)
        self.bday_month_input.setAlignment(Qt.AlignCenter)
        self.bday_day_input = QLineEdit(NewUserWidget)
        self.bday_day_input.setObjectName(u"bday_day_input")
        self.bday_day_input.setGeometry(QRect(470, 160, 71, 31))
        self.bday_day_input.setFont(font)
        self.bday_day_input.setMaxLength(2)
        self.bday_day_input.setAlignment(Qt.AlignCenter)
        self.bday_year_input = QLineEdit(NewUserWidget)
        self.bday_year_input.setObjectName(u"bday_year_input")
        self.bday_year_input.setGeometry(QRect(560, 160, 141, 31))
        self.bday_year_input.setFont(font)
        self.bday_year_input.setMaxLength(4)
        self.bday_year_input.setFrame(True)
        self.bday_year_input.setAlignment(Qt.AlignCenter)
        self.password_input = QLineEdit(NewUserWidget)
        self.password_input.setObjectName(u"password_input")
        self.password_input.setGeometry(QRect(20, 500, 321, 31))
        self.password_input.setFont(font)
        self.password_input.setTabletTracking(False)
        self.password_input.setFrame(True)
        self.password_input.setClearButtonEnabled(False)
        self.pass_label = QLabel(NewUserWidget)
        self.pass_label.setObjectName(u"pass_label")
        self.pass_label.setGeometry(QRect(20, 460, 171, 31))
        self.pass_label.setFont(font1)
        self.pass_label.setFocusPolicy(Qt.NoFocus)
        self.confirm_pass_input = QLineEdit(NewUserWidget)
        self.confirm_pass_input.setObjectName(u"confirm_pass_input")
        self.confirm_pass_input.setGeometry(QRect(20, 580, 321, 31))
        self.confirm_pass_input.setFont(font)
        self.confirm_pass_input.setTabletTracking(False)
        self.confirm_pass_input.setFrame(True)
        self.confirm_pass_input.setClearButtonEnabled(False)
        self.confirm_pass_label = QLabel(NewUserWidget)
        self.confirm_pass_label.setObjectName(u"confirm_pass_label")
        self.confirm_pass_label.setGeometry(QRect(20, 540, 271, 31))
        self.confirm_pass_label.setFont(font1)
        self.confirm_pass_label.setFocusPolicy(Qt.NoFocus)
        self.username_input = QLineEdit(NewUserWidget)
        self.username_input.setObjectName(u"username_input")
        self.username_input.setGeometry(QRect(20, 420, 321, 31))
        self.username_input.setFont(font)
        self.username_input.setTabletTracking(False)
        self.username_input.setFrame(True)
        self.username_input.setClearButtonEnabled(False)
        self.username_label = QLabel(NewUserWidget)
        self.username_label.setObjectName(u"username_label")
        self.username_label.setGeometry(QRect(20, 380, 161, 31))
        self.username_label.setFont(font1)
        self.username_label.setFocusPolicy(Qt.NoFocus)
        self.rank_cmbbx = QComboBox(NewUserWidget)
        self.rank_cmbbx.addItem("")
        self.rank_cmbbx.addItem("")
        self.rank_cmbbx.addItem("")
        self.rank_cmbbx.addItem("")
        self.rank_cmbbx.addItem("")
        self.rank_cmbbx.addItem("")
        self.rank_cmbbx.addItem("")
        self.rank_cmbbx.addItem("")
        self.rank_cmbbx.addItem("")
        self.rank_cmbbx.setObjectName(u"rank_cmbbx")
        self.rank_cmbbx.setGeometry(QRect(380, 240, 321, 31))
        self.rank_label = QLabel(NewUserWidget)
        self.rank_label.setObjectName(u"rank_label")
        self.rank_label.setGeometry(QRect(380, 200, 81, 31))
        self.rank_label.setFont(font1)
        self.label = QLabel(NewUserWidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(370, 440, 381, 171))
        font5 = QFont()
        font5.setPointSize(11)
        self.label.setFont(font5)
        self.label.setWordWrap(True)
        self.first_name_input.raise_()
        self.first_name_label.raise_()
        self.last_name_label.raise_()
        self.last_name_input.raise_()
        self.new_email_label.raise_()
        self.new_email_input.raise_()
        self.middle_name_label.raise_()
        self.phone_num_label.raise_()
        self.phone_num_input.raise_()
        self.middle_name_input.raise_()
        self.create_button.raise_()
        self.cancel_button.raise_()
        self.gender_input.raise_()
        self.gende_label.raise_()
        self.birth_date_label.raise_()
        self.bday_month_input.raise_()
        self.bday_day_input.raise_()
        self.bday_year_input.raise_()
        self.password_input.raise_()
        self.pass_label.raise_()
        self.confirm_pass_input.raise_()
        self.confirm_pass_label.raise_()
        self.username_input.raise_()
        self.username_label.raise_()
        self.rank_cmbbx.raise_()
        self.rank_label.raise_()
        self.label.raise_()
        QWidget.setTabOrder(self.first_name_input, self.middle_name_input)
        QWidget.setTabOrder(self.middle_name_input, self.last_name_input)
        QWidget.setTabOrder(self.last_name_input, self.bday_month_input)
        QWidget.setTabOrder(self.bday_month_input, self.bday_day_input)
        QWidget.setTabOrder(self.bday_day_input, self.bday_year_input)
        QWidget.setTabOrder(self.bday_year_input, self.gender_input)
        QWidget.setTabOrder(self.gender_input, self.new_email_input)
        QWidget.setTabOrder(self.new_email_input, self.phone_num_input)
        QWidget.setTabOrder(self.phone_num_input, self.create_button)
        QWidget.setTabOrder(self.create_button, self.cancel_button)

        self.retranslateUi(NewUserWidget)

        QMetaObject.connectSlotsByName(NewUserWidget)
    # setupUi

    def retranslateUi(self, NewUserWidget):
        NewUserWidget.setWindowTitle(QCoreApplication.translate("NewUserWidget", u"Create New User", None))
        self.first_name_label.setText(QCoreApplication.translate("NewUserWidget", u"First Name", None))
        self.last_name_label.setText(QCoreApplication.translate("NewUserWidget", u"Last Name", None))
        self.new_email_label.setText(QCoreApplication.translate("NewUserWidget", u"Email", None))
        self.middle_name_label.setText(QCoreApplication.translate("NewUserWidget", u"Middle Name", None))
        self.phone_num_label.setText(QCoreApplication.translate("NewUserWidget", u"Phone Number", None))
        self.create_button.setText(QCoreApplication.translate("NewUserWidget", u"Create", None))
        self.cancel_button.setText(QCoreApplication.translate("NewUserWidget", u"Cancel", None))
        self.gender_input.setText("")
        self.gende_label.setText(QCoreApplication.translate("NewUserWidget", u"Gender", None))
        self.birth_date_label.setText(QCoreApplication.translate("NewUserWidget", u"Birth Date (mm/dd/yyyy)", None))
        self.bday_month_input.setText("")
        self.bday_day_input.setText("")
        self.bday_year_input.setText("")
        self.pass_label.setText(QCoreApplication.translate("NewUserWidget", u"Password", None))
        self.confirm_pass_label.setText(QCoreApplication.translate("NewUserWidget", u"Confirm Password", None))
        self.username_label.setText(QCoreApplication.translate("NewUserWidget", u"Username", None))
        self.rank_cmbbx.setItemText(0, "")
        self.rank_cmbbx.setItemText(1, QCoreApplication.translate("NewUserWidget", u"Probationary Firefighter", None))
        self.rank_cmbbx.setItemText(2, QCoreApplication.translate("NewUserWidget", u"FireFighter", None))
        self.rank_cmbbx.setItemText(3, QCoreApplication.translate("NewUserWidget", u"Driver Engineer", None))
        self.rank_cmbbx.setItemText(4, QCoreApplication.translate("NewUserWidget", u"Lieutenant", None))
        self.rank_cmbbx.setItemText(5, QCoreApplication.translate("NewUserWidget", u"Captain", None))
        self.rank_cmbbx.setItemText(6, QCoreApplication.translate("NewUserWidget", u"Battalion Chief", None))
        self.rank_cmbbx.setItemText(7, QCoreApplication.translate("NewUserWidget", u"Assistant Chief", None))
        self.rank_cmbbx.setItemText(8, QCoreApplication.translate("NewUserWidget", u"Fire Chief", None))

        self.rank_label.setText(QCoreApplication.translate("NewUserWidget", u"Rank", None))
        self.label.setText(QCoreApplication.translate("NewUserWidget", u"Password Suggestions:\n"
"Use a password that contains upper and lower case letters\n"
"Use a password that contains at least one number\n"
"Use a password that contains at least one specical character ( ! # % ...)\n"
"Use a password that is unique from any of your other passwords used for other accounts\n"
"", None))
    # retranslateUi

